[mcp_servers.chrome-devtools]
args = ["chrome-devtools-mcp@latest"]
command = "npx"

[mcp_servers.convex]
args = [
    "-y",
    "convex@latest",
    "mcp",
    "start",
]
command = "npx"

[mcp_servers.next-devtools]
args = [
    "-y",
    "next-devtools-mcp@latest",
]
command = "npx"

[mcp_servers.shadcn]
args = [
    "shadcn@latest",
    "mcp",
]
command = "npx"
